# Generated by Django 3.2.9 on 2021-11-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=5, unique=True)),
                ('aclass', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('insurance', models.CharField(max_length=20)),
                ('vaccinationstatus', models.CharField(max_length=5)),
                ('lastvaccinated', models.DateField()),
                ('lastdoctorvisit', models.DateField()),
            ],
        ),
    ]
