# Generated by Django 3.2.9 on 2021-11-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='lastdoctorvisit',
            new_name='ddate',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='lastvaccinated',
            new_name='vdate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='vaccinationstatus',
        ),
        migrations.AddField(
            model_name='stock',
            name='a_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='vacstatus',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
