# Generated by Django 3.2.9 on 2021-11-27 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_auto_20211127_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='a_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
