# Generated by Django 3.2.9 on 2021-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20211127_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='insurance',
            field=models.DateField(),
        ),
    ]
