# Generated by Django 3.2.9 on 2021-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20211127_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='vdate',
            field=models.CharField(max_length=10),
        ),
    ]
